name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Setup JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 11
      - name: Cache build deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.konan/cache
            ~/.konan/dependencies
          key: build-deps-${{ hashFiles('~/.gradle/**') }}-${{ hashFiles('~/.konan/**') }}
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Build
        run: ./gradlew build
