name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Setup JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 17
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache build deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/wrapper
            ~/.konan/cache
            ~/.konan/dependencies
          key: build-deps-${{ runner.os }}-${{ hashFiles('gradle/**', 'gradlew*', 'gradle.properties', '*.gradle*') }}
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew check